'use client';

import { useState } from 'react';



export const DisclaimerScreen = ({ onAccept, onBack }: { onAccept: () => void; onBack: () => void }) => {
  const [agreed, setAgreed] = useState(false);

  return (
    <div className="flex flex-col items-center justify-center min-h-screen px-4 space-y-12 animate-in fade-in slide-in-from-bottom-8 duration-700">
      <div className="flex flex-col items-center space-y-6 text-center">
        <div className="w-12 h-12 rounded-full border border-blue-500/30 flex items-center justify-center bg-blue-500/5 mb-4">
          <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-blue-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
          </svg>
        </div>
        
        <h1 className="text-4xl font-semibold text-white">Important Disclaimer</h1>
      </div>

      <div className="w-full max-w-3xl glass p-10 rounded-2xl space-y-8 text-gray-400 leading-relaxed text-center">
        <p>
          The investment profile and recommendations generated by this assessment are for 
          informational purposes only and do not constitute financial advice.
        </p>
        <p>
          All investments involve risk, including the potential loss of principal. Past performance 
          does not guarantee future results. Before making any investment decisions, please 
          consult with a qualified financial advisor who can assess your individual circumstances.
        </p>
        <p>
          By continuing, you acknowledge that you understand these risks and that this 
          assessment is designed to provide general guidance based on your responses, not 
          personalized financial advice.
        </p>
      </div>

      <div className="w-full max-w-xl">
        <button 
          onClick={() => setAgreed(!agreed)}
          className="flex items-center justify-center space-x-4 w-full p-6 rounded-xl border border-white/5 hover:bg-white/5 transition-all group"
        >
          <div className={`
            w-6 h-6 rounded border-2 transition-all flex items-center justify-center
            ${agreed ? 'bg-blue-600 border-blue-600' : 'border-white/20 group-hover:border-white/40'}
          `}>
            {agreed && (
              <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-white" viewBox="0 0 20 20" fill="currentColor">
                <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
              </svg>
            )}
          </div>
          <span className="text-white font-medium">I understand and agree to the terms outlined above</span>
        </button>
      </div>

      {/* Footer Navigation */}
      <div className="flex justify-between items-center w-full max-w-2xl pt-8">
        <button
          onClick={onBack}
          className="p-4 rounded-full border border-white/20 text-white hover:bg-white/10 transition-all"
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
        </button>

        
        
        <button
          onClick={onAccept}
          disabled={!agreed}
          className={`
            flex items-center space-x-3 px-8 py-3 rounded-full border transition-all
            ${agreed 
              ? 'bg-blue-600 border-blue-500 text-white hover:bg-blue-500 shadow-[0_0_20px_rgba(59,130,246,0.4)]' 
              : 'border-white/10 text-gray-700 cursor-not-allowed'
            }
          `}
        >
          <span className="font-semibold">Next</span>
          <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14 5l7 7m0 0l-7 7m7-7H3" />
          </svg>
        </button>


        
      </div>
    </div>
  );
};
